### ISSUE TITLE
Add a reaction in #new-suggestion-feed if a dupe request has been submitted on the suggestion.

### ISSUE THREAD

**Issue by spudpotato** [Dougley/MBv2#99] opened 2019-04-10 09:41 UTC
**Is your feature request related to a problem? Please describe.**
It's annoying when you see a suggestion in new suggestion feed and you know it's a dupe, so you find the master and submit a dupe request, only to find one has already been submitted.

**Describe the solution you'd like**
A reaction like the :reported: one on the suggestion in #new-suggestion-feed and on the ```!info``` command to show that a dupe request has been submitted on it.

**Additional context**
It might also be a good idea if there was another reaction for when the suggestion has been merged by an employee.

**Comment by MoonlightCapital** [comment] 2019-05-24 08:14
Dupe of #48

**Closed** 2019-05-26 09:21 UTC
Labels: feature request
