### ISSUE TITLE
Category Change Command

### ISSUE THREAD

**Issue by Shadow-T-M** [Dougley/MBv2#102] opened 2019-04-15 20:26 UTC
**Is your feature request related to a problem? Please describe.**
Currently, if we find a feedback post in the wrong category we have to DM Dannysaur or Solarion about it.

**Describe the solution you'd like**
It would be nice to have a command that would submit a category change request to a suggestion. So in addition to the dupe/report queue, it also queues category changes. Something like `!category <suggestion> <category>`

**Additional context**
!hug Modinators

**Comment by Dougley** [comment] 2019-04-15 20:27
Duplicate of #42

**Closed by Dougley** 2019-04-15 20:27 UTC
